name: todo_app
description: A simple TODO app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.17.6
  provider: ^6.1.1
  share_plus: ^7.2.2
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  app_links: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
