// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdBoT4cWGsD4Sp2AF8XyvZsrD952bAEU',
    appId: '1:65910243874:web:6c0cdd20945e537747407b',
    messagingSenderId: '65910243874',
    projectId: 'todo-app-fresh',
    authDomain: 'todo-app-fresh.firebaseapp.com',
    databaseURL: 'https://todo-app-fresh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-fresh.firebasestorage.app',
    measurementId: 'G-LPWXJEBKB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArM17y2HL-MmvMRCAaH2zw-gfnbXykjeA',
    appId: '1:65910243874:android:a4aa047f4981e62747407b',
    messagingSenderId: '65910243874',
    projectId: 'todo-app-fresh',
    databaseURL: 'https://todo-app-fresh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-fresh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PJX9qmgN-hQ2DqNLAHp7UronaHo7qms',
    appId: '1:65910243874:ios:1170dd6911c8f98847407b',
    messagingSenderId: '65910243874',
    projectId: 'todo-app-fresh',
    databaseURL: 'https://todo-app-fresh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-fresh.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PJX9qmgN-hQ2DqNLAHp7UronaHo7qms',
    appId: '1:65910243874:ios:1170dd6911c8f98847407b',
    messagingSenderId: '65910243874',
    projectId: 'todo-app-fresh',
    databaseURL: 'https://todo-app-fresh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-fresh.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzdBoT4cWGsD4Sp2AF8XyvZsrD952bAEU',
    appId: '1:65910243874:web:188e3708fe61784147407b',
    messagingSenderId: '65910243874',
    projectId: 'todo-app-fresh',
    authDomain: 'todo-app-fresh.firebaseapp.com',
    databaseURL: 'https://todo-app-fresh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-fresh.firebasestorage.app',
    measurementId: 'G-GMPECSSPCY',
  );
}
